### ISSUE TITLE
Deploy Web Service Error

### ISSUE THREAD

**Issue by lemoncalamitous** [hning86/azuremlps#23]
It seems that I found a bug which I need an immediate solution. What I've found out is that when I am using web service deployment command in PS,

```
New-AmlWebService -PredictiveExperimentId $exp.ExperimentId
# or
New-AmlWebService -PredictiveExperimentId $exp.ExperimentId -Update
```

![deploy web svc](https://cloud.githubusercontent.com/assets/24726531/24856449/60df5ca4-1e17-11e7-89b8-48c32677e3b3.JPG)

what happens is that it will first run the experiment before deploying it.

![expt status](https://cloud.githubusercontent.com/assets/24726531/24856469/7173ba6a-1e17-11e7-8e28-f8471c403105.JPG)

Kindly inform me if this is really a bug or I need to perform/setup something on my end.

**Comment by hning86** [comment]
Yes this is intended behavior.
