### ISSUE TITLE
Ability to manage AzureML Projects ?

### ISSUE THREAD

**Issue by eligne-pro** [hning86/azuremlps#25]
I did not see any clue regarding Projects in AzureML. Is there a way to do basic operations on projects (create/delete/list/list content/add content/remove content) ? Or is there a way to manipulate datasets and experiments in a way that takes Projects into account (eg obtain the project name of a dataset/experiment in its metadata so as to be able to filter on it, ability to change the project of a dataset/experiment)?

**Comment by hning86** [comment]
Sorry there is no immediate plan to address this.
