### ISSUE TITLE
Unable to run experiment on Azure ML Studio after copying from different workspace

### ISSUE THREAD

**Issue by gokudeveloper** [hning86/azuremlps#28]
My simple experiment reads from an Azure Storage Table, Selects a few columns and writes to another Azure Storage Table. This experiment runs fine on the Workspace (Let's call it workspace1).

Now I need to move this experiment as is to another workspace(Call it WorkSpace2) using Powershell and need to be able to run the experiment. I am currently using this Library - https://github.com/hning86/azuremlps

Problem :

When I Copy the experiment using 'Copy-AmlExperiment' from WorkSpace 1 to WorkSpace 2, the experiment and all it's properties get copied except the Azure Table Account Key. Now, this experiment runs fine if I manually enter the account Key for the Import/Export Modules on studio.azureml.net

But I am unable to perform this via powershell. If I Export(Export-AmlExperimentGraph) the copied experiment from WorkSpace2 as a JSON and insert the AccountKey into the JSON file and Import(Import-AmlExperiment) it into WorkSpace 2. The experiment fails to run. Starting Experiment (Start-AmlExperiment) on PowerShell I get an "Internal Server Error : 500".

While running on studio.azureml.net, I get the notification as "Your experiment cannot be run because it has been updated in another session. Please re-open this experiment to see the latest version."

I think the problem is something to do with how the experiment handles the AccountKey. When I enter it manually, it's converted into a JSON array comprising of RecordKey and IndexInRecord. But when I upload the JSON experiment with the accountKey, it continues to remain the same and does not get resolved into RecordKey and IndexInRecord.

Is there anyway to move an experiment with external dependencies to another workspace and run it?

**Comment by hning86** [comment]
not with credential in it. we specifically wipe the credentials during the copy to avoid security threat. you will have to manually enter the account keys.
