### ISSUE TITLE
Powershell warning The names of some imported commands from the module 'AzureMLPS' include unapproved verbs

### ISSUE THREAD

**Issue by itzkunalsatpute** [hning86/azuremlps#41]
Hi Team,

I wanted to backup all my AzureML experiments to local system and hence came across this package.
I am performing below steps and getting errors
1: Downloaded the package 
2: Extracted 
3 Went to the directory where these extracted files are through powershell ise x86
4 \AzureMLPS_0.3.7> Unblock-File .\AzureMLPS.dll getting next line no errors
5 \AzureMLPS_0.3.7> Import-Module .\AzureMLPS.dll getting error as below
WARNING: The names of some imported commands from the module 'AzureMLPS' include unapproved verbs that might make them
 less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose p
arameter. For a list of approved verbs, type Get-Verb.

I tried the next step as well knowing that the file is not loaded properly and getting below errors
6 Edited CONFIG.JSON to the parameters which my experiment has 
7 Ran Get-AmlWorkspace
and getting error as et-AmlWorkspace : Error: [401 (Attempted access to 
https://studioapi.azureml.net/api/workspaces/2f112b5096d94e......e0de6648c155 is not authorized and has been 
denied.)]: {"Error":{"Code":"UserError","Message":"Attempted access to 
https://studioapi.azureml.net/api/workspaces/2f112b5096d94e......e0de6648c155 is not authorized and has been 
denied.","Target":null,"Details":[],"InnerError":null,"DebugInfo":null}}
At line:1 char:5
+     Get-AmlWorkspace
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AmlWorkspace], AmlRestApiException
    + FullyQualifiedErrorId : AzureML.Contract.AmlRestApiException,AzureML.PowerShell.GetWorkspace

Please help ME with this issue

**Comment by ksivasenthil** [comment]
@itzkunalsatpute, The warning you notice is not a problem nor it is causing the error you have in the output further down.
The error you receive could be caused due to a configuration issue. Ensure, the Workspace Id, Authentication token and the Location all match character by character. 
Alternatively you could regenerate authentication token by clicking the regenerate button next to any of the auth token. Refer to the wiki https://github.com/hning86/azuremlps#configuration.

**Comment by itzkunalsatpute** [comment]
Its my mistake, I just copy pasted the Authorization code which dint work because it dint copied the entire string then I copied by pressing home-end key. It worked Thank you for the great package.
