### ISSUE TITLE
Get Workspace Authorization Token

### ISSUE THREAD

**Issue by aplhung** [hning86/azuremlps#7]
Hi there,

Sorry if this is not the right place to ask, but I couldn't find another way to contact you.  Is there a way to get the workspace authorization token through the commandlet?  There is a AuthorizationToken field displayed by calling List-AmlWorkspaces but it is always  'AzureML.Contract.AuthorizationToken' and not a unique ID.

**Comment by hning86** [comment]
Sure. AuthorizationToken is an object with 2 string fields: PrimaryToken and SecondaryToken.
